---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-kubernetes-pkg"
  download_policy: "{{ foreman_products_defaults_download_policy_kubernetes }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_kubernetes }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_kubernetes | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_kubernetes }}"
  unprotected: "{{ foreman_products_defaults_unprotected_kubernetes | bool }}"


foreman_products_kubernetes_el7:
  - name: "{{ foreman_product_name_prefix | default('') }}Kubernetes"
    label: "{{ foreman_product_label_prefix | default('') }}Kubernetes"
    organization: "{{ foreman_organization_kubernetes_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Kubernetes - EL7"
        label: "{{ foreman_repo_label_prefix | default('') }}kubernetes-el7"
        url: "{{ foreman_repo_baseurl_kubernetes }}/repos/kubernetes-el7-x86_64"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_kubernetes_el7 }}"
      - name: "{{ foreman_repo_name_prefix | default('') }}Kubernetes Unstable - EL7"
        label: "{{ foreman_repo_label_prefix | default('') }}kubernetes-unstable-el7"
        url: "{{ foreman_repo_baseurl_kubernetes }}/repos/kubernetes-el7-x86_64-unstable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_kubernetes_el7 }}"

foreman_content_views_kubernetes_el7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}kubernetes_el7"
    organization: "{{ foreman_organization_kubernetes_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Kubernetes - EL7"
        product: "{{ foreman_product_name_prefix | default('') }}Kubernetes"
    allow_promote: "{{ foreman_cv_allow_promote_kubernetes_el7 }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}kubernetes_unstable_el7"
    organization: "{{ foreman_organization_kubernetes_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Kubernetes Unstable - EL7"
        product: "{{ foreman_product_name_prefix | default('') }}Kubernetes"
    allow_promote: "{{ foreman_cv_allow_promote_kubernetes_el7 }}"

