---

#######################################
### CONTENT VIEW DEFAULTS
#######################################

# foreman_cv_allow_promote: false
# foreman_ccv_allow_promote: true
# foreman_ccv_auto_publish: true

### KUBERNETES

# foreman_cv_allow_promote_kubernetes: "{{ foreman_cv_allow_promote | bool }}"

# foreman_cv_allow_promote_kubernetes_el7: "{{ foreman_cv_allow_promote_kubernetes | bool }}"
